export const config = {
  name: 'CA',
  fullName: 'Cheela Akhil',
  role: 'Data Analyst & Data Scientist',
  tagline: 'Available for opportunities',
  location: 'Hyderabad, India',
  email: 'akhilcheela@gmail.com',
  bio: [
    "I'm a Data Analyst and aspiring Data Scientist pursuing B.Tech in Computer Science at IARE, Hyderabad. I specialize in transforming complex, large-scale datasets into actionable business insights.",
    'Skilled in building end-to-end ML pipelines, statistical models, and interactive BI dashboards. Recognized globally — Amazon ML Challenge 2025, Rank 1,218 among thousands of participants.',
  ],
  stats: [
    { num: '91%', label: 'AUC-ROC on churn model' },
    { num: '1218', label: 'Amazon ML Challenge rank' },
    { num: '150K+', label: 'Records analyzed' },
    { num: '6+', label: 'End-to-end projects' },
  ],
  links: {
    linkedin: 'https://linkedin.com',
    github: 'https://github.com',
    leetcode: 'https://leetcode.com',
  },
  skills: [
    {
      num: '01',
      icon: '◈',
      title: 'Data Analysis & BI',
      sub: 'Business Intelligence',
      desc: 'Building interactive dashboards and reports that translate complex datasets into clear, executive-ready insights with Power BI and Tableau.',
      tags: ['Power BI', 'Tableau', 'DAX', 'SQL', 'Excel', 'ETL'],
    },
    {
      num: '02',
      icon: '◐',
      title: 'Machine Learning',
      sub: 'Predictive Modeling',
      desc: 'Designing end-to-end ML pipelines — from feature engineering and class imbalance handling to model explainability with SHAP values.',
      tags: ['Scikit-learn', 'XGBoost', 'SHAP', 'SMOTE', 'Streamlit'],
    },
    {
      num: '03',
      icon: '◉',
      title: 'Statistical Analysis',
      sub: 'EDA & Inference',
      desc: 'Rigorous exploratory data analysis, hypothesis testing, and statistical modeling to validate business decisions and uncover hidden patterns.',
      tags: ['Pandas', 'NumPy', 'Seaborn', 'Matplotlib', 'A/B Testing'],
    },
    {
      num: '04',
      icon: '◬',
      title: 'NLP & Time Series',
      sub: 'Advanced Analytics',
      desc: 'Text classification pipelines, sentiment analysis, and demand forecasting models using ARIMA and Facebook Prophet across multiple SKUs.',
      tags: ['NLTK', 'spaCy', 'TF-IDF', 'ARIMA', 'Prophet'],
    },
  ],
  experience: [
    {
      role: 'Data Analyst Intern',
      company: 'Intern Vision',
      date: 'Feb 2026 – Apr 2026 · Ongoing',
      bullets: [
        'Analysed business datasets to uncover trends and deliver actionable insights aligned to client objectives.',
        'Built and maintained interactive dashboards tracking key performance metrics.',
        'Collaborated cross-functionally to clean, transform, and present data findings to stakeholders.',
        'Produced documentation of analytical methodologies for seamless knowledge transfer.',
      ],
    },
    {
      role: 'Data Analyst Job Simulation',
      company: 'Tata Group · Forage',
      date: 'Feb 2026',
      bullets: [
        'Translated complex business questions from CEO & CMO into actionable data insights on revenue trends.',
        'Designed Power BI dashboards with advanced DAX measures for KPI tracking.',
        'Performed end-to-end ETL and EDA on multi-source datasets using Excel and Power Query.',
        'Delivered structured stakeholder presentations to senior leadership.',
      ],
    },
    {
      role: 'Data Analytics Job Simulation',
      company: 'Daikibo · Forage',
      date: 'Feb 2026',
      bullets: [
        'Analyzed large-scale compensation data to detect gender pay gaps using Tableau.',
        'Designed interactive dashboards visualizing salary distributions across departments.',
        'Applied data validation and cleaning techniques for sensitive financial reporting.',
      ],
    },
  ],
  projects: [
    {
      num: '01 / 06',
      title: 'Customer Churn Prediction',
      domain: 'Telecom · ML Classification',
      desc: 'End-to-end churn pipeline on 70K+ records. 91% AUC-ROC. SHAP explainability identified contract type & tenure as top drivers — insights adopted by the retention team.',
      stack: ['XGBoost', 'SHAP', 'SMOTE', 'Streamlit', 'Scikit-learn'],
    },
    {
      num: '02 / 06',
      title: 'Credit Delinquency Risk Analysis',
      domain: 'FinTech · Financial Analytics',
      desc: 'EDA on 150K+ borrower records. Identified Revolving Utilization >80% as strongest default predictor — correlating with 2× increase in risk.',
      stack: ['Pandas', 'NumPy', 'Matplotlib', 'Seaborn'],
    },
    {
      num: '03 / 06',
      title: 'E-Commerce Sales Dashboard',
      domain: 'Retail · BI Analytics',
      desc: '6-page Power BI report with star schema. Identified 3 underperforming regions & 5 high-margin categories — insights projected to redirect $200K+ in marketing spend.',
      stack: ['Power BI', 'DAX', 'SQL', 'Power Query'],
    },
    {
      num: '04 / 06',
      title: 'NLP Sentiment Analysis',
      domain: 'NLP · Product Intelligence',
      desc: 'Text classification pipeline on 50K+ product reviews. TF-IDF + Logistic Regression achieved 87% accuracy. Benchmarked Naive Bayes, SVM, and Random Forest.',
      stack: ['NLTK', 'spaCy', 'Scikit-learn', 'TF-IDF'],
    },
    {
      num: '05 / 06',
      title: 'House Price Prediction',
      domain: 'Real Estate · Predictive Analytics',
      desc: 'Regression models including Random Forest & Gradient Boosting. Best model achieved 22% RMSE reduction vs baseline via hyperparameter tuning and VIF checks.',
      stack: ['Scikit-learn', 'Random Forest', 'GridSearchCV'],
    },
    {
      num: '06 / 06',
      title: 'Time Series Demand Forecasting',
      domain: 'Supply Chain · Retail',
      desc: 'ARIMA & Facebook Prophet forecasting demand across 12 SKUs at 8.3% MAPE. Forecast dashboard reduced simulated stockout events by ~20% through proactive replenishment.',
      stack: ['Prophet', 'ARIMA', 'Statsmodels', 'Matplotlib'],
    },
  ],
  techRows: [
    ['Python', 'SQL', 'Power BI', 'Tableau', 'Pandas', 'NumPy', 'Scikit-learn', 'XGBoost', 'Streamlit', 'Git & GitHub'],
    ['SHAP', 'NLTK', 'spaCy', 'Prophet', 'ARIMA', 'Seaborn', 'Matplotlib', 'DAX', 'Power Query', 'PostgreSQL'],
  ],
}
